"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type User={id:string;username:string;role:string};type Post={id:string;username:string;content:string;createdAt:string};
export default function Home(){
 const [posts,setPosts]=useState<Post[]>([]),[user,setUser]=useState<User|null>(null),[content,setContent]=useState(""),[mode,setMode]=useState<"login"|"register"|"recover"|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[posting,setPosting]=useState(false),[backupKey,setBackupKey]=useState("");
 useEffect(()=>{(async()=>{const [p,u]=await Promise.all([fetch("/api/posts",{cache:"no-store"}),fetch("/api/auth/me",{cache:"no-store"})]);const pd=await p.json();const ud=await u.json();setPosts(pd.posts||[]);setUser(ud.user||null);setLoading(false)})();const node=document.querySelector(".site-stage");const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("in")),{threshold:.1});node?.querySelectorAll("[data-reveal]").forEach(e=>io.observe(e));let tx=0,ty=0,x=0,y=0,raf=0;const move=(e:MouseEvent)=>{tx=(e.clientX/innerWidth-.5)*2;ty=(e.clientY/innerHeight-.5)*2};const frame=()=>{x+=(tx-x)*.035;y+=(ty-y)*.035;node?.setAttribute("style","--mx:"+x.toFixed(4)+";--my:"+y.toFixed(4));raf=requestAnimationFrame(frame)};addEventListener("mousemove",move,{passive:true});raf=requestAnimationFrame(frame);return()=>{io.disconnect();removeEventListener("mousemove",move);cancelAnimationFrame(raf)}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!user){setMode("login");return}setPosting(true);const r=await fetch("/api/posts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})});const d=await r.json().catch(()=>({}));setPosting(false);if(!r.ok){setError(d.message||"Could not publish.");return}setPosts(p=>[d.post,...p]);setContent("")}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setUser(null)}
 return <main className="site-stage"><div className="ambient ambient-a"/><div className="ambient ambient-b"/><div className="grain"/>
 <header className="nav shell"><Link href="/" className="brand-mark"><span className="brand-symbol">S</span><span>SPEAK UP</span></Link><nav className="nav-links"><a href="#share">Share</a><a href="#experiences">Experiences</a><Link href="/admin">Admin</Link></nav><span className="nav-state"><i className="ping-dot"/> PUBLIC RECORD</span></header>
 <section className="hero shell"><div className="hero-copy fade-up"><div className="intro-kicker">S / A PUBLIC RECORD OF EXPERIENCE</div><h1>Speak <span className="grad-text">up.</span></h1><p>A privacy-first space for people to share what freedom of speech looks like where they live.</p><div className="hero-meta"><span><i className="ping-dot"/> {posts.length.toLocaleString()} EXPERIENCES</span><span>NO EMAIL REQUIRED</span><span>CHRONOLOGICAL</span></div></div><div className="signal-card fade-up-d1"><div className="signal-orbit"/><div className="signal-core">S</div><span className="signal-label">YOUR VOICE / PUBLIC</span></div></section>
 <section className="share shell" id="share" data-reveal><div className="section-heading"><div><span className="section-number">01</span><span>SHARE YOUR EXPERIENCE</span></div><p>{user?"SIGNED IN AS @"+user.username.toUpperCase():"YOUR IDENTITY IS YOURS"}</p></div>
 {!user?<div className="auth-prompt"><div><strong>Have an experience to share?</strong><span>Create an account with a username, password and private backup secret. No email required.</span></div><div><button className="btn-primary" onClick={()=>setMode("register")}>Create account ↗</button><button className="btn-outline" onClick={()=>setMode("login")}>Sign in</button></div></div>:<form className="composer" onSubmit={submit}><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={5000} placeholder="Write about your experience… What happened? What does speaking freely look like where you live?"/><div className="composer-foot"><span>{content.length.toLocaleString()} / 5,000</span><div><button type="button" className="text-button" onClick={logout}>Sign out</button><button className="btn-primary" disabled={posting||!content.trim()}>{posting?"Publishing…":"Publish experience ↗"}</button></div></div></form>}
 {error&&<div className="error-box">{error}</div>}</section>
 <section className="experiences shell" id="experiences" data-reveal><div className="section-heading"><div><span className="section-number">02</span><span>EXPERIENCES</span></div><p>NEWEST FIRST / {posts.length.toLocaleString()} RECORDS</p></div>
 {loading?<div className="empty">LOADING RECORD…</div>:posts.length?<div className="post-list">{posts.map((p,i)=><article className="post row-enter" key={p.id} style={{animationDelay:(Math.min(i,12)*45)+"ms"}}><div className="post-index">{String(posts.length-i).padStart(3,"0")}</div><div className="post-body"><div className="post-meta"><strong>@{p.username}</strong><span>{new Date(p.createdAt).toLocaleString([], {year:"numeric",month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"})}</span></div><p>{p.content}</p></div></article>)}</div>:<div className="empty"><span>00 / RECORD</span><strong>No experiences have been published yet.</strong><p>Be the first person to speak up.</p></div>}</section>
 <section className="principles shell" data-reveal><div className="section-heading"><div><span className="section-number">03</span><span>PRINCIPLES</span></div></div><div className="principle-grid"><div><span>01</span><strong>PRIVATE BY DEFAULT</strong><p>No email or phone number is required to participate.</p></div><div><span>02</span><strong>FIRST-PERSON RECORD</strong><p>The platform records people's experiences rather than assigning countries a score.</p></div><div><span>03</span><strong>CHRONOLOGICAL</strong><p>New experiences appear first. There is no popularity algorithm.</p></div></div></section>
 <footer className="footer shell"><span>SPEAK UP / 2026</span><span>PUBLIC RECORD / END</span></footer>
 {mode&&<AuthModal mode={mode} close={()=>{setMode(null);setError("")}} success={(u,key)=>{setUser(u);setMode(null);if(key)setBackupKey(key)}}/>}
 {backupKey&&<div className="modal-backdrop"><div className="backup-card"><div className="eyebrow">BACKUP SECRET / SAVE THIS NOW</div><h2>Your account recovery key.</h2><p>This key is shown once. Store it somewhere private. It can reset your password without email.</p><code>{backupKey}</code><button className="btn-primary" onClick={()=>setBackupKey("")}>I SAVED IT →</button></div></div>}
 </main>
}
function AuthModal({mode,close,success}:{mode:"login"|"register"|"recover";close:()=>void;success:(u:User,key?:string)=>void}){
 const [kind,setKind]=useState(mode),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[backup,setBackup]=useState(""),[newPassword,setNewPassword]=useState(""),[error,setError]=useState("");
 async function go(e:React.FormEvent){e.preventDefault();setError("");let url="/api/auth/login";let body:any={username,password};if(kind==="register")url="/api/auth/register";if(kind==="recover"){url="/api/auth/recover";body={username,backupKey:backup,newPassword}}const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.message||"Something went wrong.");return}if(kind==="recover"){setError("Password reset. You can now sign in.");setKind("login");setPassword("");setBackup("");setNewPassword("");return}success(d.user,d.backupKey)}
 return <div className="modal-backdrop"><div className="auth-card"><button className="modal-close" onClick={close}>×</button><div className="eyebrow">{kind==="login"?"SIGN IN":kind==="register"?"CREATE ACCOUNT":"RECOVER ACCOUNT"}</div><h2>{kind==="login"?"Welcome back.":kind==="register"?"Speak without an inbox.":"Use your backup secret."}</h2><p>{kind==="register"?"No email. No phone. Your username is the public identity attached to your posts.":kind==="recover"?"Enter your username and backup secret to choose a new password.":"Sign in with the credentials you created."}</p><form onSubmit={go}><label>USERNAME<input autoFocus value={username} onChange={e=>setUsername(e.target.value)} required/></label>{kind!=="recover"&&<label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>}{kind==="recover"&&<><label>BACKUP SECRET<input value={backup} onChange={e=>setBackup(e.target.value)} placeholder="XXXX-XXXX-XXXX-XXXX-XXXX-XXXX" required/></label><label>NEW PASSWORD<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required/></label></>}{error&&<div className="error-box">{error}</div>}<button className="btn-primary">{kind==="login"?"SIGN IN →":kind==="register"?"CREATE ACCOUNT →":"RESET PASSWORD →"}</button></form><div className="auth-switch">{kind==="login"?<><button onClick={()=>setKind("recover")}>Forgot password?</button><button onClick={()=>setKind("register")}>Create account</button></>:kind==="register"?<button onClick={()=>setKind("login")}>Already have an account? Sign in</button>:<button onClick={()=>setKind("login")}>Back to sign in</button>}</div></div></div>
}